import os
import json
import gradio as gr
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# We configure OpenAI client to use an alternative base_url if provided,
# defaulting to OpenRouter since the requested model formats (e.g. org/model) 
# strongly suggest an OpenRouter or similar endpoint.
BASE_URL = os.getenv("OPENAI_BASE_URL", "https://openrouter.ai/api/v1")
API_KEY = os.getenv("OPENROUTER_API_KEY") or os.getenv("OPENAI_API_KEY")

client = OpenAI(api_key=API_KEY, base_url=BASE_URL)

def analyzer_agent(problem: str, model: str, num_solutions: int = 2) -> list:
    """Agent 1: Breaks down the problem into different approaches."""
    prompt = (
        f"You are an expert problem analyzer. The user has a problem: '{problem}'.\n"
        f"Come up with {num_solutions} completely distinct approaches to solve this problem.\n"
        "Return the result as a JSON object with a single key 'approaches' containing a list of strings, "
        "where each string describes one unique approach."
    )
    
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are a helpful assistant designed to output JSON."},
                {"role": "user", "content": prompt}
            ],
            # If the specific model doesn't support json_object natively, it will just do its best
            response_format={"type": "json_object"} 
        )
        result = json.loads(response.choices[0].message.content)
        return result.get("approaches", [])
    except Exception as e:
        # Fallback if json parsing fails
        return [f"Fallback Approach 1 (Error parsing JSON: {e})", "Fallback Approach 2"]

def solver_agent(problem: str, approach: str, model: str) -> str:
    """Agent 2: Solves the problem using a specific approach."""
    prompt = (
        f"You are an expert problem solver.\n"
        f"Problem: {problem}\n"
        f"Approach to use: {approach}\n"
        "Provide a detailed, step-by-step solution to the problem using ONLY the specified approach."
    )
    
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are an expert problem solver."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error generating solution: {str(e)}"

def synthesize_agent(problem: str, solutions: list, model: str) -> str:
    """Agent 3: Summarizes all the findings."""
    solutions_text = "\n\n".join([f"Solution {i+1}:\n{sol}" for i, sol in enumerate(solutions)])
    prompt = (
        f"Problem: {problem}\n\n"
        f"Here are multiple solutions generated by different models and approaches:\n{solutions_text}\n\n"
        "Provide a brief executive summary comparing these solutions, highlighting the pros and cons of each."
    )
    
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are an expert at synthesizing information."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error during synthesis: {str(e)}"

def solve_problem(problem: str, analyzer_models: list, solver_models: list, synthesizer_model: str, num_solutions: int):
    if not problem.strip():
        yield "Please enter a problem.", ""
        return
        
    output_log = f"### 🎯 Problem: {problem}\n\n"
    yield output_log, ""
    
    all_approaches = []
    
    for analyzer_model in analyzer_models:
        output_log += f"**🔍 Analyzer Agent ({analyzer_model})** is brainstorming approaches...\n\n"
        yield output_log, ""
        
        approaches = analyzer_agent(problem, analyzer_model, int(num_solutions))
        
        for i, app in enumerate(approaches):
            approach_text = f"[{analyzer_model}] {app}"
            all_approaches.append(approach_text)
            output_log += f"**Approach {len(all_approaches)}:** {approach_text}\n\n"
        yield output_log, ""
    
    if not all_approaches:
        yield output_log + "No approaches were generated.", ""
        return
        
    all_solutions = []
    
    # Have the selected solver models solve each approach
    for i, approach in enumerate(all_approaches):
        output_log += f"---\n### Developing Approach {i+1}\n\n"
        yield output_log, ""
        
        for model in solver_models:
            output_log += f"**💡 Solver Agent ({model})** is working on it...\n\n"
            yield output_log, ""
            
            solution = solver_agent(problem, approach, model)
            all_solutions.append(f"Model: {model} | Approach: {approach}\nSolution:\n{solution}")
            
            output_log += f"<details><summary>View Solution from {model}</summary>\n\n{solution}\n\n</details>\n\n"
            yield output_log, ""
            
    output_log += f"---\n### 📝 Synthesizer Agent ({synthesizer_model}) is summarizing...\n\n"
    yield output_log, ""
    
    synthesis = synthesize_agent(problem, all_solutions, synthesizer_model)
    
    yield output_log, synthesis

def build_ui():
    models = ["nvidia/nemotron-3-super-120b-a12b", "qwen/qwen3.7-flash"]
    
    with gr.Blocks(title="Multi-AI Problem Solver", theme=gr.themes.Soft()) as app:
        gr.Markdown("# 🤖 Multi-AI Problem Solver")
        gr.Markdown("This system uses multiple AI models to analyze a problem, generate diverse solutions using different models, and synthesize the results. By default, it's configured for OpenRouter compatible endpoints.")
        
        with gr.Row():
            with gr.Column(scale=1):
                problem_input = gr.Textbox(
                    label="What is your problem?", 
                    lines=4, 
                    placeholder="e.g. How can we effectively scale our microservices database architecture?"
                )
                
                with gr.Group():
                    gr.Markdown("### Agent Configuration")
                    analyzer_checkboxes = gr.CheckboxGroup(
                        choices=models, 
                        value=models, 
                        label="Analyzer Models (Brainstorms different approaches)"
                    )
                    solver_checkboxes = gr.CheckboxGroup(
                        choices=models, 
                        value=models, 
                        label="Solver Models (Generates a solution for each approach)"
                    )
                    synthesizer_dropdown = gr.Dropdown(
                        choices=models, 
                        value=models[1], 
                        label="Synthesizer Model (Summarizes solutions)"
                    )
                    num_approaches = gr.Slider(minimum=1, maximum=5, value=2, step=1, label="Number of Approaches per Analyzer")
                
                submit_btn = gr.Button("🚀 Generate Solutions", variant="primary")
                
            with gr.Column(scale=2):
                log_output = gr.Markdown(label="Execution Log")
                final_synthesis = gr.Markdown(label="Final Synthesis")
                
        submit_btn.click(
            solve_problem,
            inputs=[problem_input, analyzer_checkboxes, solver_checkboxes, synthesizer_dropdown, num_approaches],
            outputs=[log_output, final_synthesis]
        )
        
    return app

if __name__ == "__main__":
    app = build_ui()
    app.launch(inbrowser=True)
