import os
import json
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables (ensure OPENAI_API_KEY is set in your .env)
load_dotenv()

class MultiAgentProblemSolver:
    def __init__(self, analyzer_models=None, solver_models=None, synthesizer_model="gpt-4o-mini"):
        if analyzer_models is None:
            analyzer_models = ["gpt-4o-mini"]
        if solver_models is None:
            solver_models = ["gpt-4o-mini"]
            
        self.client = OpenAI()
        self.analyzer_models = analyzer_models
        self.solver_models = solver_models
        self.synthesizer_model = synthesizer_model

    def analyzer_agent(self, problem: str, model: str, num_solutions: int = 3) -> list:
        """
        Agent 1: Analyzes the problem and proposes different distinct approaches.
        """
        print(f"🔍 [Analyzer Agent ({model})] Brainstorming different approaches...")
        prompt = (
            f"You are an expert problem analyzer. The user has a problem: '{problem}'.\n"
            f"Come up with {num_solutions} completely distinct approaches to solve this problem.\n"
            "Return the result as a JSON object with a single key 'approaches' containing a list of strings, "
            "where each string describes one unique approach."
        )
        
        response = self.client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are a helpful assistant designed to output JSON."},
                {"role": "user", "content": prompt}
            ],
            response_format={"type": "json_object"}
        )
        
        try:
            result = json.loads(response.choices[0].message.content)
            return result.get("approaches", [])
        except Exception as e:
            print(f"Error parsing analyzer response from {model}: {e}")
            return []

    def solver_agent(self, problem: str, approach: str, model: str) -> str:
        """
        Agent 2: Generates a detailed solution based on a specific approach.
        """
        print(f"💡 [Solver Agent ({model})] Developing solution based on approach:\n{approach[:100]}...\n")
        prompt = (
            f"You are an expert problem solver.\n"
            f"Problem: {problem}\n"
            f"Approach to use: {approach}\n"
            "Provide a detailed, step-by-step solution to the problem using ONLY the specified approach."
        )
        
        response = self.client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are an expert problem solver."},
                {"role": "user", "content": prompt}
            ]
        )
        
        return response.choices[0].message.content

    def synthesize_agent(self, problem: str, solutions: list, model: str) -> str:
        """
        Agent 3: Synthesizes and summarizes the solutions.
        """
        print(f"📝 [Synthesizer Agent ({model})] Summarizing all solutions...")
        solutions_text = "\n\n".join([f"Solution {i+1}:\n{sol}" for i, sol in enumerate(solutions)])
        prompt = (
            f"Problem: {problem}\n\n"
            f"Here are multiple solutions generated by different agents:\n{solutions_text}\n\n"
            "Provide a brief executive summary comparing these solutions, highlighting the pros and cons of each."
        )
        
        response = self.client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are an expert at synthesizing information."},
                {"role": "user", "content": prompt}
            ]
        )
        
        return response.choices[0].message.content

    def solve(self, problem: str, num_solutions: int = 2):
        print(f"\n🎯 PROBLEM: {problem}\n" + "="*50)
        
        all_approaches = []
        # Step 1: Get different approaches from all analyzer models
        for analyzer_model in self.analyzer_models:
            approaches = self.analyzer_agent(problem, analyzer_model, num_solutions)
            for app in approaches:
                all_approaches.append((analyzer_model, app))
        
        if not all_approaches:
            print("Failed to generate approaches.")
            return
            
        all_solutions = []
        # Step 2: Generate a solution for each approach using all solver models
        for i, (analyzer_model, approach) in enumerate(all_approaches):
            print(f"\n--- Approach {i+1} (from {analyzer_model}) ---")
            print(f"Strategy: {approach}")
            
            for solver_model in self.solver_models:
                solution = self.solver_agent(problem, approach, solver_model)
                all_solutions.append(f"Model: {solver_model} | Approach: {approach}\nSolution:\n{solution}")
                print(f"Solution Summary ({solver_model}): {solution[:150]}...\n")
            
        # Step 3: Synthesize
        print("\n" + "="*50)
        synthesis = self.synthesize_agent(problem, all_solutions, self.synthesizer_model)
        print("\nFINAL SYNTHESIS:\n")
        print(synthesis)
        print("="*50 + "\n")
        
        return {
            "approaches": [app for _, app in all_approaches],
            "solutions": all_solutions,
            "synthesis": synthesis
        }

if __name__ == "__main__":
    solver = MultiAgentProblemSolver(
        analyzer_models=["gpt-4o-mini", "gpt-4o-mini"], # Using same model twice for testing, replace with other models
        solver_models=["gpt-4o-mini"]
    )
    test_problem = "How can we reduce traffic congestion in a rapidly growing metropolitan city?"
    solver.solve(test_problem)
