version: '3'

services:
  jupyter:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: llm-engineering
    environment:
      - JUPYTER_TOKEN=docker
      - OLLAMA_HOST=http://host.docker.internal:11434
