"""
Analyze summarized community contributions and extract ecosystem insights.

This script:
1. Loads project summaries generated by summarize_contributions.py
2. Sends them to an LLM for higher-level analysis
3. Saves insights to results/ecosystem_insights.md
"""
from dotenv import load_dotenv
import json
from pathlib import Path
from openai import OpenAI
import os

# --------------------------------------------------
# Configuration
# --------------------------------------------------
# load .env from project root
load_dotenv(Path(__file__).resolve().parents[4] / ".env")
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

BASE_DIR = Path(__file__).parent
RESULTS_DIR = BASE_DIR / "results"

INPUT_FILE = RESULTS_DIR / "community_contribution_summaries.json"
OUTPUT_FILE = RESULTS_DIR / "ecosystem_insights.md"

client = OpenAI()


# --------------------------------------------------
# Load summaries
# --------------------------------------------------

def load_summaries():
    if not INPUT_FILE.exists():
        raise FileNotFoundError(
            "Summaries file not found. Run summarize_contributions.py first."
        )

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


# --------------------------------------------------
# Build text input for LLM
# --------------------------------------------------

def build_summary_text(data, limit=80):
    """
    Combine project summaries into one text block.
    Limit to avoid token overflow.
    """

    summaries = "\n\n".join(
        f"{item['project_name']}:\n{item['summary']}"
        for item in data[:limit]
    )

    return summaries


# --------------------------------------------------
# Generate ecosystem insights
# --------------------------------------------------

def analyze_projects(summary_text):

    system_prompt = """
You analyze collections of GitHub community projects.

Your goal is to extract ecosystem insights.

Identify:
- recurring project themes
- interesting or unique projects
- beginner-friendly projects
- commonly used technologies
"""

    user_prompt = f"""
Analyze the following community contribution summaries.

Return:

1. Overall ecosystem summary
2. Top recurring project themes
3. Most interesting or innovative projects
4. Beginner-friendly projects
5. Common technologies used across projects

Data:

{summary_text}
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        temperature=0.2,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )

    return response.choices[0].message.content


# --------------------------------------------------
# Save insights
# --------------------------------------------------

def save_results(text):

    RESULTS_DIR.mkdir(exist_ok=True)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# Community Contribution Ecosystem Insights\n\n")
        f.write(text)

    print(f"Insights saved to {OUTPUT_FILE}")


# --------------------------------------------------
# Main pipeline
# --------------------------------------------------

def main():

    print("Loading summaries...")
    data = load_summaries()

    print("Preparing data for analysis...")
    summary_text = build_summary_text(data)

    print("Analyzing ecosystem insights...")
    insights = analyze_projects(summary_text)

    print("Saving results...")
    save_results(insights)

    print("Analysis complete.")


if __name__ == "__main__":
    main()