# -*- coding: utf-8 -*-
"""train_job_salary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lbiSvUTT8Jgwd5rJTBZlCQItUVRKcfe
"""

#!pip install -q transformers datasets peft trl bitsandbytes torch accelerate python-dotenv

import os
import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig
from huggingface_hub import login
from google.colab import userdata # Use Colab's secret manager

print(f"Is CUDA (GPU) available? {torch.cuda.is_available()}")

hf_token = userdata.get('HF_TOKEN')
if hf_token:
    login(hf_token, add_to_git_credential=True)
else:
    raise ValueError("HF_TOKEN not found. Please add it to Colab Secrets.")

DATASET_ID = "jederhion/job_salary_prompts" # Your pushed dataset
BASE_MODEL = "meta-llama/Llama-3.2-3B"
OUTPUT_DIR = "./job_salary_model"

def format_instruction(example):
    """Combines the prompt and completion for Supervised Fine-Tuning (SFT)."""
    return f"{example['prompt']}{example['completion']}"

print(f"Loading dataset: {DATASET_ID}")
dataset = load_dataset(DATASET_ID)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

print("Loading tokenizer and model...")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.bfloat16,
)

# Prepare model for training
model = prepare_model_for_kbit_training(model)

# 3. Configure Low-Rank Adaptation (LoRA) Adapters
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

# 4. Set Training Arguments
training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    logging_steps=10,
    max_steps=200,
    save_steps=50,
    bf16=True, # Use bfloat16
    fp16=False, # Disable float16 as we are using bfloat16
    optim="paged_adamw_8bit",
    max_length=250,
    dataset_text_field="text",
    report_to="none" # Disable W&B logging for now
)

# 5. Initialize the Supervised Fine-Tuning (SFT) Trainer
print("Initializing SFT Trainer...")

train_data = dataset["train"].map(lambda x: {"text": format_instruction(x)})

trainer = SFTTrainer(
    model=model,
    train_dataset=train_data,
    peft_config=peft_config,
    args=training_args,
    processing_class=tokenizer,
)

# 6. Start Training
print("Starting training on T4 GPU...")
trainer.train()

# 7. Save the final adapter weights
print(f"Saving fine-tuned adapters to {OUTPUT_DIR}")
trainer.model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training complete!")

# Define the name for your new model repository
HF_USERNAME = "jederhion"
MODEL_REPO_NAME = f"{HF_USERNAME}/job_salary_adapters"

print(f"Pushing fine-tuned adapters to {MODEL_REPO_NAME}...")

# Push the model weights
trainer.model.push_to_hub(MODEL_REPO_NAME)

# Push the tokenizer
tokenizer.push_to_hub(MODEL_REPO_NAME)

print("Successfully pushed to Hugging Face Hub!")

