"""
Pydantic models for the Bug Hunter Agent Framework.
Defines data structures for scraped bugs, analysis results, and dataset entries.
"""

from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime


class ScrapedBug(BaseModel):
    """A bug scraped from Stack Overflow."""

    code: str = Field(description="The Python code snippet containing the bug")
    title: str = Field(description="The Stack Overflow question title")
    url: str = Field(description="URL of the Stack Overflow question")
    description: str = Field(
        default="", description="Brief description from the SO question"
    )


class BugDetail(BaseModel):
    """Detail about a single bug within a code snippet."""

    line: int = Field(description="The line number where the bug occurs")
    type: str = Field(description="The type of bug (e.g., NameError, LogicError)")
    description: str = Field(description="Description of the bug")


class BugAnalysis(BaseModel):
    """Analysis of a buggy code snippet produced by the BugAnalysisAgent."""

    description: str = Field(description="What the code is trying to do")
    num_bugs: int = Field(description="Number of distinct bugs found")
    bug_types: List[str] = Field(description="List of bug type names")
    level: str = Field(description="Difficulty level: easy, medium, or hard")
    bugs_detail: List[BugDetail] = Field(description="Detailed info for each bug")
    tags: List[str] = Field(default_factory=list, description="Topic tags")


class BatchBugAnalysis(BaseModel):
    """A batch of BugAnalysis results corresponding to multiple inputted code snippets."""

    analyses: List[BugAnalysis] = Field(
        description="List of bug analyses, in the exact same order as the input snippets"
    )


class BugEntry(BaseModel):
    """
    A complete bug dataset entry matching buggy_dataset_nl.jsonl schema.
    This is the final output that can be appended to the existing dataset.
    """

    level: str
    description: str
    buggy_code: str
    correct_code: str = Field(description="The fixed, correct Python code")
    bug_types: List[str]
    num_bugs: int
    bugs_detail: List[BugDetail]
    tags: List[str]
    model: str = Field(default="openrouter/frontier")
    id: int = Field(default=0)
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    source_url: Optional[str] = Field(default=None, description="Stack Overflow URL")


class BugCorrection(BaseModel):
    """
    The corrected version of the buggy code, generated by the CodeCorrectionAgent.
    """

    correct_code: str = Field(description="The fixed, correct Python code snippet")


class BugReport(BaseModel):
    """A formatted markdown report for a discovered bug."""

    markdown: str = Field(description="The formatted markdown report")
    entry: BugEntry = Field(description="The structured JSON entry")
